name: Test build

on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - assets/**
      - nginx/**
  push:
    paths:
      - src/**
      - assets/**
      - nginx/**


jobs:
  test_docker_image:
    runs-on: ubuntu-latest;

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker compose -f compose.dev.yaml up -d --build



